name = "main-pacarerate-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "api.pacarerate.com/*", zone_name = "pacarerate.com" }
]

[[d1_databases]]
binding = "DB"
database_name = "main-pacarerate"
database_id = "00964e85-a0ba-40d7-8b26-c0f788b649d0"

# TURNSTILE_SECRET_KEY is set via `wrangler secret put` (not in this file)
